SELECT CAR_ID, C.CAR_TYPE, (DAILY_FEE * (1-(DISCOUNT_RATE/100)) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV')
    AND CAR_ID NOT IN (SELECT CAR_ID
                      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                      WHERE TO_CHAR(START_DATE, 'YYYYMMDD') <= '20221130'
                        AND TO_CHAR(END_DATE, 'YYYYMMDD') >= '20221101')
    AND DURATION_TYPE = '30일 이상'
    AND (DAILY_FEE * (1-(DISCOUNT_RATE/100)) * 30) BETWEEN 500000 AND 2000000
ORDER BY 3 DESC, 2, 1 DESC;
   
