-- 코드를 입력하세요
SELECT YEAR, MONTH, COUNT(*) AS PUCHASED_USERS,ROUND(COUNT(*)/(SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS PUCHASED_RATIO
FROM (SELECT DISTINCT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, U.USER_ID
      FROM USER_INFO U JOIN ONLINE_SALE O
      ON U.USER_ID = O.USER_ID AND YEAR(JOINED) = 2021) A
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;


