SELECT FLAVOR
FROM (SELECT F.FLAVOR, SUM(F.TOTAL_ORDER + J.TOTAL_ORDER ) AS SUM
      FROM FIRST_HALF F LEFT JOIN JULY J
      ON F.FLAVOR = J.FLAVOR
      GROUP BY F.FLAVOR
      ORDER BY SUM DESC)
WHERE ROWNUM <= 3;